// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/leungas/tofu/packages/config/services"
)

// Injectors from wire.go:

func Initialize(options []services.ConfigOptions) (ConfigModule, error) {
	configService := services.New(options)
	configModule := New(configService)
	return configModule, nil
}
